ARG BASE_IMAGE=ubuntu:20.04

FROM ${BASE_IMAGE} AS builder

ENV DEBIAN_FRONTEND=noninteractive

RUN grep deb /etc/apt/sources.list | \
    sed 's/^deb/deb-src /g' >> /etc/apt/sources.list
RUN apt-get update && \
    apt-get install -y --no-install-recommends git autoconf automake autotools-dev curl python3 python3-pip libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev ninja-build cmake libglib2.0-dev wget libzstd-dev python-is-python3 device-tree-compiler libboost-regex-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev ccache libssl-dev \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/ \
    && rm -rf /var/lib/apt/lists

# Install modern CMake
ARG ENABLE_CMAKE="false"
ARG CMAKE_REPO="https://github.com/Kitware/CMake"
ARG CMAKE_VERSION="3.27.7"
ARG CMAKE_TARGET="Linux-x86_64"
RUN if [ "${ENABLE_CMAKE}" = "true" ] ; \
    then \
    cd /tmp \
    && wget -O cmake.sh ${CMAKE_REPO}/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-${CMAKE_TARGET}.sh \
    && mkdir -p /opt/cmake/ \
    && sh ./cmake.sh --skip-license --exclude-subdir --prefix=/opt/cmake/ \
    && rm ./cmake.sh ; \
    fi
ENV PATH="/opt/cmake/bin/:$PATH:"
